---
- hosts: back
  tasks:
    - name: install apache
      apt: name=apache2 state=latest update_cache=yes
    - name: install mod_php
      apt: name=libapache2-mod-php state=present update_cache=yes
    - name: start apache2
      service: name=apache2 state=started enabled=yes
 